#!/res/sbin/busybox sh

BB=/res/sbin/busybox

if [ ! -x /sbin/recovery ]; then
	[ ! -d /sbin ] && $BB mkdir /sbin
	$BB cp -rp /res/sbin/* /sbin/
	/sbin/busybox --install -s /sbin
fi

if [ ! -b /dev/block/bml7 ]; then
	$BB cat /etc/recovery.fstab | $BB grep -v -e /boot -e /recovery > /etc/recovery.fstab
fi

exec /sbin/recovery

